---
- name: install and start apache
  hosts: flipkart-apache
  become: yes
  vars:
    http_port: 81
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: latest
    - name: latest index.html file is present
      copy:
        src: flipkart/index.html-ansible
        dest: /var/www/html/index.html
    - name: late
      service:
        name: httpd
        state: started

