---
- name: Configure Apache for httpd
  hosts: xyz-com-apache-node
  become: yes
  roles:
    - httpd
    - tomcat7

- name: Configure Apache for httpd
  hosts: xyz-com-apache-node
  become: yes
  tasks:
    - name: copy the xyz.com code
      copy:
        src: /etc/ansible/xyz-com/xyz.html
        dest: /var/www/html/xyz.html
        owner: root

- name: Copy the code-war file to tomcat Servers
  hosts: xyz-com-apache-node
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Install boto3 and botocore with pip2 module
      pip:
        name:
          - boto3
          - botocore
        #executable: pip-2.7

    - name: copy the war file
      aws_s3:
        bucket: artifactory-1030-weekly
        object: SampleWebApp123.war
        dest: /usr/share/tomcat7/webapps/SampleWebApp123.war
        mode: get

- name: Configure ProxyPass between Apache and Tomcat
  hosts: xyz-com-apache-node
  become: yes
  tasks:
    - name: copy the proxypass conf file
      copy:
        src: /etc/ansible/xyz-com/proxyPass.conf
        dest: /etc/httpd/conf.d/proxyPass.conf
        owner: root
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
